apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- backend
- frontend
- base
commonLabels:
  app: todoapp
images:
- name: todoapp-backend
  newName: asia-southeast1-docker.pkg.dev/miason/todoapp-repository/todoapp-backend
  newTag: v1.0.0
- name: todoapp-frontend
  newName: asia-southeast1-docker.pkg.dev/miason/todoapp-repository/todoapp-frontend
  newTag: v1.0.0
